#pragma once

#define lua_Integer rlua_Integer
#define lua_Unsigned rlua_Unsigned
#define lua_Number rlua_Number

#define luaL_Buffer rluaL_Buffer
#define luaL_Reg rluaL_Reg
#define luaL_Stream rluaL_Stream
#define luaL_addlstring rluaL_addlstring
#define luaL_addstring rluaL_addstring
#define luaL_addvalue rluaL_addvalue
#define luaL_argerror rluaL_argerror
#define luaL_buffinit rluaL_buffinit
#define luaL_buffinitsize rluaL_buffinitsize
#define luaL_callmeta rluaL_callmeta
#define luaL_checkany rluaL_checkany
#define luaL_checkinteger rluaL_checkinteger
#define luaL_checklstring rluaL_checklstring
#define luaL_checknumber rluaL_checknumber
#define luaL_checkoption rluaL_checkoption
#define luaL_checkstack rluaL_checkstack
#define luaL_checktype rluaL_checktype
#define luaL_checkudata rluaL_checkudata
#define luaL_checkversion_ rluaL_checkversion_
#define luaL_error rluaL_error
#define luaL_execresult rluaL_execresult
#define luaL_fileresult rluaL_fileresult
#define luaL_getmetafield rluaL_getmetafield
#define luaL_getsubtable rluaL_getsubtable
#define luaL_gsub rluaL_gsub
#define luaL_len rluaL_len
#define luaL_loadbufferx rluaL_loadbufferx
#define luaL_loadfilex rluaL_loadfilex
#define luaL_loadstring rluaL_loadstring
#define luaL_newmetatable rluaL_newmetatable
#define luaL_newstate rluaL_newstate
#define luaL_openlibs rluaL_openlibs
#define luaL_optinteger rluaL_optinteger
#define luaL_optlstring rluaL_optlstring
#define luaL_optnumber rluaL_optnumber
#define luaL_prepbuffsize rluaL_prepbuffsize
#define luaL_pushresult rluaL_pushresult
#define luaL_pushresultsize rluaL_pushresultsize
#define luaL_ref rluaL_ref
#define luaL_requiref rluaL_requiref
#define luaL_setfuncs rluaL_setfuncs
#define luaL_setmetatable rluaL_setmetatable
#define luaL_testudata rluaL_testudata
#define luaL_tolstring rluaL_tolstring
#define luaL_traceback rluaL_traceback
#define luaL_typeerror rluaL_typeerror
#define luaL_unref rluaL_unref
#define luaL_where rluaL_where
#define lua_Alloc rlua_Alloc
#define lua_CFunction rlua_CFunction
#define lua_Debug rlua_Debug
#define lua_Hook rlua_Hook
#define lua_Integer rlua_Integer
#define lua_KContext rlua_KContext
#define lua_KFunction rlua_KFunction
#define lua_Number rlua_Number
#define lua_Reader rlua_Reader
#define lua_State rlua_State
#define lua_Unsigned rlua_Unsigned
#define lua_WarnFunction rlua_WarnFunction
#define lua_Writer rlua_Writer
#define lua_absindex rlua_absindex
#define lua_arith rlua_arith
#define lua_atpanic rlua_atpanic
#define lua_callk rlua_callk
#define lua_checkstack rlua_checkstack
#define lua_close rlua_close
#define lua_compare rlua_compare
#define lua_concat rlua_concat
#define lua_copy rlua_copy
#define lua_createtable rlua_createtable
#define lua_dump rlua_dump
#define lua_error rlua_error
#define lua_gc rlua_gc
#define lua_getallocf rlua_getallocf
#define lua_getfield rlua_getfield
#define lua_getglobal rlua_getglobal
#define lua_gethook rlua_gethook
#define lua_gethookcount rlua_gethookcount
#define lua_gethookmask rlua_gethookmask
#define lua_geti rlua_geti
#define lua_getinfo rlua_getinfo
#define lua_getiuservalue rlua_getiuservalue
#define lua_getlocal rlua_getlocal
#define lua_getmetatable rlua_getmetatable
#define lua_getstack rlua_getstack
#define lua_gettable rlua_gettable
#define lua_gettop rlua_gettop
#define lua_getupvalue rlua_getupvalue
#define lua_ident rlua_ident
#define lua_iscfunction rlua_iscfunction
#define lua_isinteger rlua_isinteger
#define lua_isnumber rlua_isnumber
#define lua_isstring rlua_isstring
#define lua_isuserdata rlua_isuserdata
#define lua_isyieldable rlua_isyieldable
#define lua_len rlua_len
#define lua_load rlua_load
#define lua_newstate rlua_newstate
#define lua_newthread rlua_newthread
#define lua_newuserdatauv rlua_newuserdatauv
#define lua_next rlua_next
#define lua_pcallk rlua_pcallk
#define lua_pushboolean rlua_pushboolean
#define lua_pushcclosure rlua_pushcclosure
#define lua_pushfstring rlua_pushfstring
#define lua_pushinteger rlua_pushinteger
#define lua_pushlightuserdata rlua_pushlightuserdata
#define lua_pushlstring rlua_pushlstring
#define lua_pushnil rlua_pushnil
#define lua_pushnumber rlua_pushnumber
#define lua_pushstring rlua_pushstring
#define lua_pushthread rlua_pushthread
#define lua_pushvalue rlua_pushvalue
#define lua_pushvfstring rlua_pushvfstring
#define lua_rawequal rlua_rawequal
#define lua_rawget rlua_rawget
#define lua_rawgeti rlua_rawgeti
#define lua_rawgetp rlua_rawgetp
#define lua_rawlen rlua_rawlen
#define lua_rawset rlua_rawset
#define lua_rawseti rlua_rawseti
#define lua_rawsetp rlua_rawsetp
#define lua_resetthread rlua_resetthread
#define lua_resume rlua_resume
#define lua_rotate rlua_rotate
#define lua_setallocf rlua_setallocf
#define lua_setfield rlua_setfield
#define lua_setglobal rlua_setglobal
#define lua_sethook rlua_sethook
#define lua_seti rlua_seti
#define lua_setiuservalue rlua_setiuservalue
#define lua_setlocal rlua_setlocal
#define lua_setmetatable rlua_setmetatable
#define lua_settable rlua_settable
#define lua_settop rlua_settop
#define lua_setupvalue rlua_setupvalue
#define lua_setwarnf rlua_setwarnf
#define lua_status rlua_status
#define lua_stringtonumber rlua_stringtonumber
#define lua_toboolean rlua_toboolean
#define lua_tocfunction rlua_tocfunction
#define lua_toclose rlua_toclose
#define lua_tointegerx rlua_tointegerx
#define lua_tolstring rlua_tolstring
#define lua_tonumberx rlua_tonumberx
#define lua_topointer rlua_topointer
#define lua_tothread rlua_tothread
#define lua_touserdata rlua_touserdata
#define lua_type rlua_type
#define lua_typename rlua_typename
#define lua_upvalueid rlua_upvalueid
#define lua_upvaluejoin rlua_upvaluejoin
#define lua_version rlua_version
#define lua_warning rlua_warning
#define lua_xmove rlua_xmove
#define lua_yieldk rlua_yieldk
